---
# File: cluster_install.yml
# Example Ansible playbook to install Couchbase Server on cluster nodes
#
# NB: This installs the Couchbase Server software, but does not
# actually initialize a cluster, see cluster_init.yml for that

- hosts: cluster_nodes
  become: yes
  become_user: root
  roles:
    - couchbaselabs.couchbase-server
  tasks:
  - name: Couchbase Server Service
    service: name=couchbase-server state=started
