---
# File: cluster_collect_info.yml
# Ansible playbook to grab diagnostic & logging information from
# the specified Couchbase Server cluster nodes with cbcollect_info

- hosts: cluster_nodes
  become: yes
  become_user: root
  vars_files:
    - ../defaults/main.yml

  tasks:

  - name: Execute cbcollect_info
    shell: "TMPDIR={{ couchbase_server_tmpdir }} {{ couchbase_server_bin_path }}/cbcollect_info {{ couchbase_server_cbcollect_path }}/{{ ansible_hostname }}.zip"

  - name: Gather logs
    fetch: "src={{ couchbase_server_cbcollect_path }}/{{ ansible_hostname }}.zip dest=var/cbcollect_info/{{ ansible_hostname }}.zip flat=yes"

  - name: Cleanup
    file: "path={{ couchbase_server_cbcollect_path }}/{{ ansible_hostname }}.zip state=absent"
